[package]
name = "impl-more"
version = "0.1.0"
description = "Concise trait implementations"
authors = ["Rob Ede <robjtede@icloud.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"
rust-version = "1.56"

[dependencies]

[dev-dependencies]
# derive_more = "0.99.8"
static_assertions = "1.1"
